data:
  file_path: 'data/dummy.csv'
  file_type: 'csv'  # Options: 'csv', 'xyz', 'cif'
  test_size: 0.2
  random_state: 42

training:
  batch_size: 64
  epochs: 100
  learning_rate: 0.001

models:
  traditional:
    linear_regression:
      enabled: false
    random_forest:
      enabled: false
      n_estimators: 100
    svr:
      enabled: false
  neural_network:
    enabled: true
    layers: [128, 64]
    activation: 'relu'
    optimizer: 'adam'
  gnn:
    enabled: false
    layers: [128, 64]
    activation: 'relu'
    optimizer: 'adam'

hyperparameters:
  search:
    max_trials: 100
